### ISSUE TITLE
Installation with symfony 4 not working

### ISSUE THREAD

**Issue by timohund** [harmbandstra/swagger-ui-bundle#13]
I have the following error when i configure the bundle with symfony 4 according to the readme:

```
ServiceNotFoundException

The "HarmBandstra\SwaggerUiBundle\Controller\DocsController::getParameter()" method is missing a parameter bag to work properly. Did you forget to register your controller as a service subscriber? This can be fixed either by using autoconfiguration or by manually wiring a "parameter_bag" in the service locator passed to the controller.
```

Any idea what's wrong?

**Comment by harmbandstra** [comment]
Do you have autowiring enabled in services.yaml, like this:
```
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
```
And which version of PHP and symfony are you using?
